(()=>{'use strict';
const events=new Set(),states=new Set();
let config={resolve:null,autostart:true,connectTimeoutMs:1800},endpoint='',token='',session=false,streamEpoch=0,recovering=false,woken=false,attempt=0,lastError='',latency='',status='cold',field={};
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),now=()=>performance.now();
function cleanBase(v){return String(v||'').replace(/\/$/,'')}
function put(channel,event){let v=field;const parts=String(channel||'field').split('.').filter(Boolean);for(let i=0;i<parts.length-1;i++){const k=parts[i];if(!v[k]||typeof v[k]!=='object')v[k]={};v=v[k]}v[parts[parts.length-1]||'field']=event}
function snapshotState(){return{status,latency,session,endpoint,attempt,lastError}}
function state(next){if(next&&next!==status){status=next;for(const fn of states)try{fn(snapshotState())}catch(_){}}return snapshotState()}
function timeoutFetch(url,opt={},ms=2200){const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),ms);return fetch(url,{cache:'no-store',...opt,signal:ac.signal}).finally(()=>clearTimeout(tm))}
async function api(path,opt={},ms=2200){if(!endpoint||!token)throw Error('field endpoint unavailable');const t=now(),r=await timeoutFetch(endpoint+path,{...opt,headers:{...(opt.headers||{}),'Authorization':'Bearer '+token}},ms);latency=Math.max(0,Math.round(now()-t))+'ms';return r}
function accept(event){if(!event||typeof event!=='object'||!event.channel)return;put(event.channel,event);for(const fn of events)try{fn(event,field,snapshotState())}catch(_){}}
async function selftest(){const ms=Number(config.connectTimeoutMs||1800);const a=await api('/api/selftest',{},ms);if(!a.ok)throw Error('field selftest '+a.status);const av=await a.json();if(!av?.ok)throw Error('field selftest');const h=await api('/api/health',{},ms);if(!h.ok)throw Error('field health '+h.status);const hv=await h.json();if(!hv?.ok)throw Error('field health')}
async function open(candidate){endpoint=cleanBase(candidate?.base||'');token=String(candidate?.token||'');if(!endpoint||token.length<24)throw Error('field candidate');await selftest();const r=await api('/api/session',{method:'POST'},Number(config.connectTimeoutMs||1800));if(!r.ok)throw Error('field session '+r.status);session=true;attempt=0;lastError='';state('live');startStream();return true}
async function startStream(){const epoch=++streamEpoch;try{const r=await fetch(endpoint+'/api/field.ndjson',{cache:'no-store',headers:{'Authorization':'Bearer '+token,'Accept':'application/x-ndjson'}});if(!r.ok||!r.body)throw Error('field stream '+r.status);const reader=r.body.getReader(),dec=new TextDecoder();let buf='';while(session&&epoch===streamEpoch){const part=await reader.read();if(part.done)throw Error('field eof');buf+=dec.decode(part.value,{stream:true});for(;;){const i=buf.indexOf('\n');if(i<0)break;const line=buf.slice(0,i);buf=buf.slice(i+1);if(!line)continue;let msg;try{msg=JSON.parse(line)}catch(_){continue}if(msg.type==='field'){for(const e of msg.events||[])accept(e);state('live')}}}}catch(e){if(epoch===streamEpoch){lastError=String(e?.message||e);drop()}}}
function drop(){session=false;streamEpoch++;state(woken?'recovering':'cold')}
async function resolve(){if(typeof config.resolve!=='function')throw Error('field resolver missing');return config.resolve({attempt,lastError,current:{base:endpoint,token},field})}
async function recover(){if(recovering)return;recovering=true;let backoff=45;for(;;){if(session){await sleep(180);continue}if(!woken&&!config.autostart){await sleep(120);continue}state('recovering');try{const candidate=await resolve();attempt++;await open(candidate);backoff=45;continue}catch(e){lastError=String(e?.message||e);drop()}await sleep(backoff);backoff=Math.min(5000,Math.round(backoff*1.55))}}
async function emit(channel,shape,payload,{stream='',revision=0,final=false,meta={}}={}){wake();if(!session)throw Error('field offline');const r=await api('/api/field',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,shape,payload,stream,revision,final,meta})},1400);let value={};try{value=await r.json()}catch(_){}if(!r.ok)throw Error(String(value.error||('field '+r.status)));return value}
async function emitBinary(channel,shape,body,{stream='',revision=0,final=false,meta={}}={}){wake();if(!session)throw Error('field offline');const headers={'Content-Type':'application/octet-stream','X-Field-Channel':String(channel||'field'),'X-Field-Shape':String(shape||'opaque'),'X-Field-Stream':String(stream||''),'X-Field-Revision':String(revision||0),'X-Field-Final':final?'1':'0','X-Field-Meta':btoa(unescape(encodeURIComponent(JSON.stringify(meta||{}))))};const r=await api('/api/field',{method:'POST',headers,body},3600);let value={};try{value=await r.json()}catch(_){}if(!r.ok)throw Error(String(value.error||('field '+r.status)));return value}
function configure(value={}){config={...config,...value};if(value.autostart!==false)woken=true;recover();return apiObject}
function wake(){woken=true;if(!session)state('recovering');recover();return snapshotState()}
function subscribe(fn){events.add(fn);return()=>events.delete(fn)}
function onState(fn){states.add(fn);try{fn(snapshotState())}catch(_){}return()=>states.delete(fn)}
const apiObject={configure,wake,emit,emitBinary,subscribe,onState,latest:()=>field,state:snapshotState,connected:()=>session,drop};
window.ARCHIE_FIELD=apiObject;window.ARCHIE_FIELD_CORE=apiObject;
})();
