(()=>{'use strict';
const core=window.ARCHIE_FIELD_CORE,$=id=>document.getElementById(id),root=$('root'),screen=$('screen'),canvas=$('scene'),ctx=canvas?.getContext('2d'),layers=$('layers'),sceneStyle=$('sceneStyle');
if(!core||!root||!canvas||!ctx||!layers||!sceneStyle)return;
let scene={revision:0,css:'',layers:[],nodes:[],features:{}},sceneSig='',screenEpoch=0,local={};
function get(o,p){let v=o;for(const k of String(p||'').split('.')){if(!k)continue;if(v==null)return '';v=v[k]}return v==null?'':v}
function model(){const s=core.state();return{field:core.latest(),status:s.status,latency:s.latency,...local}}
function display(v){if(v==null)return '';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v);try{return JSON.stringify(v,null,1)}catch(_){return String(v)}}
function projectRows(v,d){if(!Array.isArray(v))return v;const n=Number(d.tail||0);if(Number.isFinite(n)&&n>0)v=v.slice(-Math.min(80,Math.floor(n)));const h=Number(d.head||0);if(Number.isFinite(h)&&h>0)v=v.slice(0,Math.min(80,Math.floor(h)));if(Array.isArray(d.fields)&&d.fields.length){const fieldSep=typeof d.fieldSeparator==='string'?d.fieldSeparator:'  ',rowSep=typeof d.rowSeparator==='string'?d.rowSeparator:'\n';v=v.map(item=>d.fields.map(p=>display(get(item,p))).filter(Boolean).join(fieldSep)).filter(Boolean).join(rowSep)}return v}
function selected(m,d){let v=get(m,d.bind||'');v=projectRows(v,d);if(d.last&&Array.isArray(v))v=v.length?v[v.length-1]:'';if(d.first&&Array.isArray(v))v=v.length?v[0]:'';if(d.pick)v=get(v,d.pick);if(d.map&&Object.prototype.hasOwnProperty.call(d.map,String(v)))v=d.map[String(v)];if(typeof d.prefix==='string'&&v!=='')v=d.prefix+v;if(typeof d.suffix==='string'&&v!=='')v=v+d.suffix;return v}
function fit(){const v=visualViewport;if(!v){root.style.height='100%';root.style.top='0';return}root.style.height=Math.max(1,v.height)+'px';root.style.top=Math.max(0,v.offsetTop)+'px'}
fit();visualViewport?.addEventListener('resize',fit);visualViewport?.addEventListener('scroll',fit);
function ensureCanvas(){const dpr=Math.max(1,Math.min(3,devicePixelRatio||1)),w=root.clientWidth,h=root.clientHeight,nw=Math.round(w*dpr),nh=Math.round(h*dpr);if(canvas.width!==nw||canvas.height!==nh){canvas.width=nw;canvas.height=nh;canvas.style.width=w+'px';canvas.style.height=h+'px'}ctx.setTransform(dpr,0,0,dpr,0,0)}
function num(v,d=0){if(typeof v==='number')return v;if(typeof v==='string'){const n=Number(get(model(),v));return Number.isFinite(n)?n:d}return d}
function draw(){ensureCanvas();const m=model(),w=root.clientWidth,h=root.clientHeight;ctx.clearRect(0,0,w,h);for(const n of Array.isArray(scene.nodes)?scene.nodes:[]){if(!n||typeof n!=='object'||(n.when&&!get(m,n.when)))continue;ctx.globalAlpha=Math.max(0,Math.min(1,num(n.alpha,1)));ctx.fillStyle=String(n.fill||'rgba(255,255,255,.12)');ctx.strokeStyle=String(n.stroke||'rgba(255,255,255,.35)');ctx.lineWidth=Math.max(.25,num(n.line,1));const x=num(n.x,.5)*w,y=num(n.y,.5)*h,r=num(n.r,.02)*Math.min(w,h);if(n.kind==='disc'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}else if(n.kind==='ring'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke()}else if(n.kind==='grid'){const cols=Math.max(1,Math.floor(num(n.cols,3))),rows=Math.max(1,Math.floor(num(n.rows,3))),sx=num(n.sx,.02)*w,sy=num(n.sy,.02)*h;for(let iy=0;iy<rows;iy++)for(let ix=0;ix<cols;ix++){ctx.beginPath();ctx.arc(x+(ix-(cols-1)/2)*sx,y+(iy-(rows-1)/2)*sy,r,0,Math.PI*2);ctx.fill()}}}ctx.globalAlpha=1;requestAnimationFrame(draw)}requestAnimationFrame(draw);
function build(){layers.replaceChildren();for(const d of Array.isArray(scene.layers)?scene.layers:[]){if(!d?.id)continue;const el=document.createElement('div');el.className='scene-layer '+String(d.class||'');el.dataset.sceneId=String(d.id);if(d.style&&typeof d.style==='object')Object.assign(el.style,d.style);layers.appendChild(el)}}
function render(){const m=model();for(const d of Array.isArray(scene.layers)?scene.layers:[]){const el=layers.querySelector('[data-scene-id="'+CSS.escape(String(d.id))+'"]');if(!el)continue;const text=display(selected(m,d));el.textContent=text;el.hidden=!!d.hideEmpty&&!text}}
function apply(value){if(!value||typeof value!=='object')return;const sig=JSON.stringify(value);if(sig===sceneSig)return;scene=value;sceneSig=sig;sceneStyle.textContent=String(value.css||'').slice(0,120000);build();render()}
function screenRef(payload){const p=payload&&payload.path;if(!p)return;const s=core.state(),base=String(s.endpoint||'').replace(/\/$/,''),token=(window.ARCHIE_FIELD_ENDPOINT?.token?.()||'');if(!base||!token)return;const e=++screenEpoch;screen.src=base+p+(p.includes('?')?'&':'?')+'t='+encodeURIComponent(token)+'&e='+e;screen.classList.add('live')}
screen.onerror=()=>{screen.classList.remove('live');const e=get(model(),'field.machine.screen');if(core.connected()&&e?.payload)setTimeout(()=>screenRef(e.payload),140)};
core.subscribe(e=>{if(e.channel==='surface.scene'&&e.payload&&typeof e.payload==='object')apply(e.payload);if(e.channel==='machine.screen'&&e.payload)screenRef(e.payload);render()});core.onState(()=>render());
function setLocal(path,value){const parts=String(path||'value').split('.').filter(Boolean);let v=local;for(let i=0;i<parts.length-1;i++){const k=parts[i];if(!v[k]||typeof v[k]!=='object')v[k]={};v=v[k]}v[parts[parts.length-1]||'value']=value;render()}
window.ARCHIE_FIELD_SURFACE={apply,render,setLocal,model,fit};
})();
