(()=>{'use strict';
const core=window.ARCHIE_FIELD_CORE,surface=window.ARCHIE_FIELD_SURFACE,ink=document.getElementById('ink'),key=document.getElementById('key');
if(!core||!surface||!ink||!key)return;
let symbolStream=crypto.randomUUID(),symbolRevision=0,pendingSymbol=null,symbolSending=false,composing=false;
let micOn=false,micStream=null,audioCtx=null,processor=null,source=null,contactWanted=false,contactEpoch=0,contactStream='',contactParts=[],contactBytes=0,previewMark=0,contactReady=null,sampleQueue=[],sampleSending=false;
let holdTimer=0,holdStarted=false,keyPointer=null;
const MAX_CONTACT_BYTES=640000,PREVIEW_STEP=16000,PREVIEW_WINDOW=96000;
function connected(){return core.connected()}
function wake(){core.wake()}
function setDraft(value){surface.setLocal('draft.value',value)}
function setHeld(value){surface.setLocal('control.held',!!value);key.classList.toggle('held',!!value)}
function queueSymbol(final=false){wake();const value=ink.value.replace(/\u00a0/g,' ');setDraft(value);symbolRevision++;pendingSymbol={channel:'user.primary',shape:'utf8',payload:{value},stream:symbolStream,revision:symbolRevision,final,meta:{source:'ios-adapter',client_sent_ms:Date.now()}};flushSymbol();if(final){ink.value='';setDraft('');symbolStream=crypto.randomUUID();symbolRevision=0}}
async function flushSymbol(){if(symbolSending||!connected()||!pendingSymbol)return;symbolSending=true;try{while(connected()&&pendingSymbol){const p=pendingSymbol;pendingSymbol=null;await core.emit(p.channel,p.shape,p.payload,p)}}catch(_){core.drop()}finally{symbolSending=false}}
ink.addEventListener('compositionstart',()=>composing=true);ink.addEventListener('compositionend',()=>{composing=false;queueSymbol(false)});ink.addEventListener('input',()=>{wake();if(!composing)queueSymbol(false)});ink.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();queueSymbol(true)}});ink.addEventListener('focus',wake);
function resample(input,from,to=16000){if(from===to)return input;const ratio=from/to,n=Math.max(1,Math.floor(input.length/ratio)),out=new Float32Array(n);for(let i=0;i<n;i++){const a=Math.floor(i*ratio),b=Math.min(input.length-1,Math.floor((i+1)*ratio));let sum=0,c=0;for(let j=a;j<=b;j++){sum+=input[j];c++}out[i]=c?sum/c:0}return out}
function pcm16(f){const a=new Int16Array(f.length);for(let i=0;i<f.length;i++){const x=Math.max(-1,Math.min(1,f[i]));a[i]=x<0?x*32768:x*32767}return new Uint8Array(a.buffer)}
function appendContact(bytes){if(!bytes?.length)return;contactParts.push(bytes);contactBytes+=bytes.length;while(contactBytes>MAX_CONTACT_BYTES&&contactParts.length>1){const q=contactParts.shift();contactBytes-=q.length}}
function tailContact(maxBytes=PREVIEW_WINDOW){const n=Math.min(maxBytes,contactBytes),out=new Uint8Array(n);let pos=n;for(let i=contactParts.length-1;i>=0&&pos>0;i--){const q=contactParts[i],take=Math.min(q.length,pos);pos-=take;out.set(q.subarray(q.length-take),pos)}return pos?out.subarray(pos):out}
function queueSample(bytes,opts){sampleQueue.push({bytes,opts});drainSamples()}
async function drainSamples(){if(sampleSending||!connected())return;sampleSending=true;try{while(connected()&&sampleQueue.length){const q=sampleQueue[0];await core.emitBinary('user.primary','pcm_s16le',q.bytes,q.opts);sampleQueue.shift()}}catch(_){core.drop()}finally{sampleSending=false}}
async function beginContact(epoch){wake();if(!contactWanted||epoch!==contactEpoch)return;contactStream=crypto.randomUUID();contactParts=[];contactBytes=0;previewMark=0;try{contactReady=core.emit('user.contact','application/vnd.archie.contact+json',{active:true,client_started_ms:Date.now()},{stream:contactStream,revision:1,final:false});await contactReady}catch(_){core.drop();return}if(!contactWanted||epoch!==contactEpoch)return;let stream=null,ac=null,src=null,proc=null;try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(!contactWanted||epoch!==contactEpoch){stream.getTracks().forEach(t=>t.stop());return}ac=new(window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});if(ac.state==='suspended')await ac.resume();if(!contactWanted||epoch!==contactEpoch){stream.getTracks().forEach(t=>t.stop());await ac.close().catch(()=>{});return}src=ac.createMediaStreamSource(stream);proc=ac.createScriptProcessor(1024,1,1);proc.onaudioprocess=e=>{if(!micOn||!contactWanted||epoch!==contactEpoch)return;const bytes=pcm16(resample(e.inputBuffer.getChannelData(0),ac.sampleRate,16000));appendContact(bytes);if(contactBytes-previewMark>=PREVIEW_STEP&&contactBytes>=6400){previewMark=contactBytes;queueSample(tailContact(),{stream:contactStream,revision:2+previewMark,final:false,meta:{rate:16000,preview:true}})}};src.connect(proc);proc.connect(ac.destination);micStream=stream;audioCtx=ac;source=src;processor=proc;micOn=true;setHeld(true)}catch(_){if(stream)stream.getTracks().forEach(t=>t.stop());if(ac)await ac.close().catch(()=>{});if(epoch===contactEpoch)setHeld(false)}}
function stopMic(){micOn=false;setHeld(false);if(processor)try{processor.disconnect()}catch(_){}if(source)try{source.disconnect()}catch(_){}if(micStream)micStream.getTracks().forEach(t=>t.stop());if(audioCtx)audioCtx.close().catch(()=>{});processor=source=micStream=audioCtx=null}
async function endContact(){const stream=contactStream,final=tailContact(MAX_CONTACT_BYTES);contactWanted=false;++contactEpoch;stopMic();try{if(contactReady)await contactReady}catch(_){}if(stream&&final.length>=6400){try{await core.emitBinary('user.primary','pcm_s16le',final,{stream,revision:999999,final:true,meta:{rate:16000}})}catch(_){core.drop()}}if(stream){try{await core.emit('user.contact','application/vnd.archie.contact+json',{active:false,client_ended_ms:Date.now()},{stream,revision:1000000,final:true})}catch(_){core.drop()}}contactStream='';contactParts=[];contactBytes=0;contactReady=null}
function beginHold(){holdStarted=true;contactWanted=true;const epoch=++contactEpoch;beginContact(epoch)}
function down(e){e.preventDefault();wake();keyPointer=e.pointerId;holdStarted=false;clearTimeout(holdTimer);holdTimer=setTimeout(beginHold,145);try{key.setPointerCapture(e.pointerId)}catch(_){}}
function up(e){if(keyPointer!==null&&e.pointerId!==keyPointer)return;e.preventDefault();clearTimeout(holdTimer);keyPointer=null;if(holdStarted||contactWanted||micOn){endContact();holdStarted=false;return}if(ink.value.trim())queueSymbol(true);else{ink.focus({preventScroll:true});wake()}}
key.addEventListener('pointerdown',down);key.addEventListener('pointerup',up);key.addEventListener('pointercancel',e=>{e.preventDefault();clearTimeout(holdTimer);keyPointer=null;if(holdStarted||contactWanted||micOn)endContact();holdStarted=false});key.addEventListener('contextmenu',e=>e.preventDefault());
core.onState(s=>{if(s.session){flushSymbol();drainSamples()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&(contactWanted||micOn))endContact()});
window.ARCHIE_FIELD_ADAPTER={name:'ios-single-control',flush:()=>{flushSymbol();drainSamples()},stop:()=>{if(contactWanted||micOn)endContact()}};
})();
