(()=>{'use strict';
const $=id=>document.getElementById(id),root=$('root'),screen=$('screen'),canvas=$('scene'),ctx=canvas.getContext('2d'),layers=$('layers'),ink=$('ink'),key=$('key'),sceneStyle=$('sceneStyle');
let token='',session=false,fieldEpoch=0,screenEpoch=0,recovering=false,recoverBackoff=80;
let sceneDef={revision:0,css:'',layers:[],nodes:[],features:{}},sceneRevision=-1;
let model={status:'cold',latency:'',field:{},draft:{value:''},control:{held:false}};
let textStream=crypto.randomUUID(),textRevision=0,pending=null,sending=false,composing=false;
let micOn=false,micStream=null,audioCtx=null,processor=null,source=null,contactWanted=false,contactEpoch=0,contactStream='',contactParts=[],contactBytes=0,previewMark=0,contactReady=null,sampleQueue=[],sampleSending=false;
let holdTimer=0,holdStarted=false,keyPointer=null;
const MAX_CONTACT_BYTES=640000,PREVIEW_STEP=16000,PREVIEW_WINDOW=96000;
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),now=()=>performance.now();
function hashToken(){let h=location.hash.replace(/^#/,'');if(h.startsWith('t='))h=h.slice(2);try{h=decodeURIComponent(h)}catch(_){}return /^[A-Za-z0-9_-]{24,160}$/.test(h)?h:''}
function initToken(){const h=hashToken();if(h){token=h;localStorage.setItem('archie.native.token',token);history.replaceState(null,'',location.pathname+location.search);return}try{const v=localStorage.getItem('archie.native.token')||'';if(/^[A-Za-z0-9_-]{24,160}$/.test(v))token=v}catch(_){}}
initToken();
function path(o,p){let v=o;for(const k of String(p||'').split('.')){if(!k)continue;if(v==null)return '';v=v[k]}return v==null?'':v}
function putChannel(channel,event){let v=model.field;const parts=String(channel||'field').split('.').filter(Boolean);for(let i=0;i<parts.length-1;i++){const k=parts[i];if(!v[k]||typeof v[k]!=='object')v[k]={};v=v[k]}v[parts[parts.length-1]||'field']=event}
function display(v){if(v==null)return '';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v);try{return JSON.stringify(v,null,1)}catch(_){return String(v)}}
function fit(){const v=visualViewport;if(!v){root.style.height='100%';root.style.top='0';return}root.style.height=Math.max(1,v.height)+'px';root.style.top=Math.max(0,v.offsetTop)+'px'}fit();visualViewport?.addEventListener('resize',fit);visualViewport?.addEventListener('scroll',fit);
function timeoutFetch(url,opt={},ms=2200){const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),ms);return fetch(url,{cache:'no-store',...opt,signal:ac.signal}).finally(()=>clearTimeout(tm))}
async function api(p,opt={},ms=2200){if(!token)throw Error('token');const t=now(),r=await timeoutFetch(p,{...opt,headers:{...(opt.headers||{}),'Authorization':'Bearer '+token}},ms);model.latency=Math.round(now()-t)+'ms';return r}
function ensureCanvas(){const dpr=Math.max(1,Math.min(3,devicePixelRatio||1)),w=root.clientWidth,h=root.clientHeight,nw=Math.round(w*dpr),nh=Math.round(h*dpr);if(canvas.width!==nw||canvas.height!==nh){canvas.width=nw;canvas.height=nh;canvas.style.width=w+'px';canvas.style.height=h+'px'}ctx.setTransform(dpr,0,0,dpr,0,0)}
function num(v,d=0){if(typeof v==='number')return v;if(typeof v==='string'){const n=Number(path(model,v));return Number.isFinite(n)?n:d}return d}
function draw(){ensureCanvas();const w=root.clientWidth,h=root.clientHeight;ctx.clearRect(0,0,w,h);for(const n of Array.isArray(sceneDef.nodes)?sceneDef.nodes:[]){if(!n||typeof n!=='object'||(n.when&&!path(model,n.when)))continue;ctx.globalAlpha=Math.max(0,Math.min(1,num(n.alpha,1)));ctx.fillStyle=String(n.fill||'rgba(255,255,255,.12)');ctx.strokeStyle=String(n.stroke||'rgba(255,255,255,.35)');ctx.lineWidth=Math.max(.25,num(n.line,1));const x=num(n.x,.5)*w,y=num(n.y,.5)*h,r=num(n.r,.02)*Math.min(w,h);if(n.kind==='disc'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}else if(n.kind==='ring'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke()}else if(n.kind==='grid'){const cols=Math.max(1,Math.floor(num(n.cols,3))),rows=Math.max(1,Math.floor(num(n.rows,3))),sx=num(n.sx,.02)*w,sy=num(n.sy,.02)*h;for(let iy=0;iy<rows;iy++)for(let ix=0;ix<cols;ix++){ctx.beginPath();ctx.arc(x+(ix-(cols-1)/2)*sx,y+(iy-(rows-1)/2)*sy,r,0,Math.PI*2);ctx.fill()}}}ctx.globalAlpha=1;requestAnimationFrame(draw)}requestAnimationFrame(draw);
function buildLayers(){layers.replaceChildren();for(const d of Array.isArray(sceneDef.layers)?sceneDef.layers:[]){if(!d?.id)continue;const el=document.createElement('div');el.className='scene-layer '+String(d.class||'');el.dataset.sceneId=String(d.id);if(d.style&&typeof d.style==='object')Object.assign(el.style,d.style);layers.appendChild(el)}}
function render(){for(const d of Array.isArray(sceneDef.layers)?sceneDef.layers:[]){const el=layers.querySelector('[data-scene-id="'+CSS.escape(String(d.id))+'"]');if(!el)continue;let v=path(model,d.bind||'');if(d.map&&Object.prototype.hasOwnProperty.call(d.map,String(v)))v=d.map[String(v)];if(typeof d.prefix==='string'&&v!=='')v=d.prefix+v;if(typeof d.suffix==='string'&&v!=='')v=v+d.suffix;const text=display(v);el.textContent=text;el.hidden=!!d.hideEmpty&&!text}}
function applyScene(v){if(!v||typeof v!=='object')return;const sig=JSON.stringify(v);if(Number(v.revision||0)===sceneRevision&&sig===JSON.stringify(sceneDef))return;sceneDef=v;sceneRevision=Number(v.revision||0);sceneStyle.textContent=String(v.css||'').slice(0,120000);buildLayers();render()}
async function selftest(){const a=await api('/api/selftest',{},1500);if(!a.ok)throw Error('selftest');const s=await a.json();if(!s.ok)throw Error('selftest');const h=await api('/api/health',{},1500);if(!h.ok||(await h.json()).ok!==true)throw Error('health')}
async function openSession(){if(!token)throw Error('token');await selftest();const r=await api('/api/session',{method:'POST'},1800);if(!r.ok)throw Error('session');session=true;recoverBackoff=80;model.status='live';startField();flush();render()}
function startScreenRef(payload){const p=payload&&payload.path;if(!p||!token)return;const e=++screenEpoch;screen.src=p+(p.includes('?')?'&':'?')+'t='+encodeURIComponent(token)+'&e='+e;screen.classList.add('live')}
screen.onerror=()=>{screen.classList.remove('live');const e=path(model,'field.machine.screen');if(session&&e?.payload)setTimeout(()=>startScreenRef(e.payload),140)};
function acceptEvent(e){if(!e||typeof e!=='object'||!e.channel)return;putChannel(e.channel,e);if(e.channel==='surface.scene'&&e.payload&&typeof e.payload==='object')applyScene(e.payload);if(e.channel==='machine.screen'&&e.payload)startScreenRef(e.payload);if(e.channel==='controller.state'&&e.payload){const events=Array.isArray(e.payload.events)?e.payload.events:[];if(events.length)putChannel('controller.event',{channel:'controller.event',payload:events[events.length-1],at:e.at})}render()}
async function startField(){const epoch=++fieldEpoch;try{const r=await fetch('/api/field.ndjson',{cache:'no-store',headers:{'Authorization':'Bearer '+token,'Accept':'application/x-ndjson'}});if(!r.ok||!r.body)throw Error('field');const reader=r.body.getReader(),dec=new TextDecoder();let buf='';while(session&&epoch===fieldEpoch){const {value,done}=await reader.read();if(done)throw Error('eof');buf+=dec.decode(value,{stream:true});for(;;){const i=buf.indexOf('\n');if(i<0)break;const line=buf.slice(0,i);buf=buf.slice(i+1);if(!line)continue;let v;try{v=JSON.parse(line)}catch(_){continue}if(v.type==='field'){for(const e of v.events||[])acceptEvent(e);model.status='live';render()}}}}catch(_){if(epoch===fieldEpoch){session=false;model.status='recovering';render()}}}
async function recover(){if(recovering)return;recovering=true;for(;;){if(session){await sleep(220);continue}model.status=token?'recovering':'cold';render();if(token&&navigator.onLine){try{await openSession();continue}catch(_){}}await sleep(recoverBackoff);recoverBackoff=Math.min(5000,Math.round(recoverBackoff*1.55))}}recover();
async function emit(channel,shape,payload,{stream='',revision=0,final=false,meta={}}={}){if(!session)throw Error('offline');const r=await api('/api/field',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,shape,payload,stream,revision,final,meta})},1400);if(!r.ok)throw Error('field '+r.status);return r.json()}
async function emitBinary(channel,shape,body,{stream='',revision=0,final=false,meta={}}={}){if(!session)throw Error('offline');const headers={'Content-Type':'application/octet-stream','X-Field-Channel':channel,'X-Field-Shape':shape,'X-Field-Stream':stream,'X-Field-Revision':String(revision),'X-Field-Final':final?'1':'0'};if(meta.rate)headers['X-Field-Rate']=String(meta.rate);if(meta.preview)headers['X-Field-Preview']='1';const r=await api('/api/field',{method:'POST',headers,body},3200);if(!r.ok)throw Error('field '+r.status);return r.json()}
window.ARCHIE_FIELD={emit,emitBinary,latest:()=>model.field,state:()=>({status:model.status,latency:model.latency}),tokenPresent:()=>!!token};
function queue(final=false){const value=ink.value.replace(/\u00a0/g,' ');model.draft={value};render();textRevision++;pending={channel:'user.primary',shape:'utf8',payload:{value},stream:textStream,revision:textRevision,final,meta:{source:'direct-surface',client_sent_ms:Date.now()}};flush();if(final){ink.value='';model.draft={value:''};textStream=crypto.randomUUID();textRevision=0;render()}}
async function flush(){if(sending||!session||!pending)return;sending=true;try{while(session&&pending){const p=pending;pending=null;await emit(p.channel,p.shape,p.payload,p)}}catch(_){session=false}finally{sending=false}}
ink.addEventListener('compositionstart',()=>composing=true);ink.addEventListener('compositionend',()=>{composing=false;queue(false)});ink.addEventListener('input',()=>{if(!composing)queue(false)});ink.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();queue(true)}});
function resample(input,from,to=16000){if(from===to)return input;const ratio=from/to,n=Math.max(1,Math.floor(input.length/ratio)),out=new Float32Array(n);for(let i=0;i<n;i++){const a=Math.floor(i*ratio),b=Math.min(input.length-1,Math.floor((i+1)*ratio));let sum=0,c=0;for(let j=a;j<=b;j++){sum+=input[j];c++}out[i]=c?sum/c:0}return out}
function pcm16(f){const a=new Int16Array(f.length);for(let i=0;i<f.length;i++){const x=Math.max(-1,Math.min(1,f[i]));a[i]=x<0?x*32768:x*32767}return new Uint8Array(a.buffer)}
function appendContact(bytes){if(!bytes?.length)return;contactParts.push(bytes);contactBytes+=bytes.length;while(contactBytes>MAX_CONTACT_BYTES&&contactParts.length>1){const q=contactParts.shift();contactBytes-=q.length}}
function tailContact(maxBytes=PREVIEW_WINDOW){const n=Math.min(maxBytes,contactBytes),out=new Uint8Array(n);let pos=n;for(let i=contactParts.length-1;i>=0&&pos>0;i--){const q=contactParts[i],take=Math.min(q.length,pos);pos-=take;out.set(q.subarray(q.length-take),pos)}return pos?out.subarray(pos):out}
function queueSample(bytes,opts){sampleQueue.push({bytes,opts});drainSamples()}
async function drainSamples(){if(sampleSending||!session)return;sampleSending=true;try{while(session&&sampleQueue.length){const q=sampleQueue[0];await emitBinary('user.primary','pcm_s16le',q.bytes,q.opts);sampleQueue.shift()}}catch(_){session=false}finally{sampleSending=false}}
async function beginContact(epoch){if(!contactWanted||epoch!==contactEpoch)return;contactStream=crypto.randomUUID();contactParts=[];contactBytes=0;previewMark=0;contactReady=emit('user.contact','application/vnd.archie.contact+json',{active:true,client_started_ms:Date.now()},{stream:contactStream,revision:1,final:false});try{await contactReady}catch(_){session=false;return}if(!contactWanted||epoch!==contactEpoch)return;let stream=null,ac=null,src=null,proc=null;try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(!contactWanted||epoch!==contactEpoch){stream.getTracks().forEach(t=>t.stop());return}ac=new(window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});if(ac.state==='suspended')await ac.resume();if(!contactWanted||epoch!==contactEpoch){stream.getTracks().forEach(t=>t.stop());await ac.close().catch(()=>{});return}src=ac.createMediaStreamSource(stream);proc=ac.createScriptProcessor(1024,1,1);proc.onaudioprocess=e=>{if(!micOn||!contactWanted||epoch!==contactEpoch)return;const bytes=pcm16(resample(e.inputBuffer.getChannelData(0),ac.sampleRate,16000));appendContact(bytes);if(contactBytes-previewMark>=PREVIEW_STEP&&contactBytes>=6400){previewMark=contactBytes;queueSample(tailContact(),{stream:contactStream,revision:2+previewMark,final:false,meta:{rate:16000,preview:true}})}};src.connect(proc);proc.connect(ac.destination);micStream=stream;audioCtx=ac;source=src;processor=proc;micOn=true;model.control.held=true;key.classList.add('held');render()}catch(_){if(stream)stream.getTracks().forEach(t=>t.stop());if(ac)await ac.close().catch(()=>{});if(epoch===contactEpoch){model.control.held=false;key.classList.remove('held');render()}}}
function stopMic(){micOn=false;model.control.held=false;key.classList.remove('held');render();if(processor)try{processor.disconnect()}catch(_){}if(source)try{source.disconnect()}catch(_){}if(micStream)micStream.getTracks().forEach(t=>t.stop());if(audioCtx)audioCtx.close().catch(()=>{});processor=source=micStream=audioCtx=null}
async function endContact(){const stream=contactStream,final=tailContact(MAX_CONTACT_BYTES);contactWanted=false;++contactEpoch;stopMic();try{if(contactReady)await contactReady}catch(_){}if(stream&&final.length>=6400){try{await emitBinary('user.primary','pcm_s16le',final,{stream,revision:999999,final:true,meta:{rate:16000}})}catch(_){session=false}}if(stream){try{await emit('user.contact','application/vnd.archie.contact+json',{active:false,client_ended_ms:Date.now()},{stream,revision:1000000,final:true})}catch(_){session=false}}contactStream='';contactParts=[];contactBytes=0;contactReady=null}
function beginHold(){holdStarted=true;contactWanted=true;const epoch=++contactEpoch;beginContact(epoch)}
function keyDown(e){e.preventDefault();keyPointer=e.pointerId;holdStarted=false;clearTimeout(holdTimer);holdTimer=setTimeout(beginHold,145);try{key.setPointerCapture(e.pointerId)}catch(_){}}
function keyUp(e){if(keyPointer!==null&&e.pointerId!==keyPointer)return;e.preventDefault();clearTimeout(holdTimer);keyPointer=null;if(holdStarted||contactWanted||micOn){endContact();holdStarted=false;return}if(ink.value.trim())queue(true);else ink.focus({preventScroll:true})}
key.addEventListener('pointerdown',keyDown);key.addEventListener('pointerup',keyUp);key.addEventListener('pointercancel',e=>{e.preventDefault();clearTimeout(holdTimer);keyPointer=null;if(holdStarted||contactWanted||micOn)endContact();holdStarted=false});key.addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('online',()=>{session=false;recoverBackoff=30});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(contactWanted||micOn)endContact()}else{session=false;recoverBackoff=30;fit()}});
})();
