(()=>{'use strict';
const TAIL='https://desktop-6fn9b4m-1.tail1bf489.ts.net:8444';
const RAW='https://raw.githubusercontent.com/Pokitomas/archie-backend-xfer-1787735782/master/';
const $=id=>document.getElementById(id),root=$('root'),screen=$('screen'),canvas=$('scene'),ctx=canvas.getContext('2d'),layers=$('layers'),ink=$('ink'),key=$('key'),sceneStyle=$('sceneStyle');
let bridge='',token='',topic='',agent='gpt56sol-interface-live',session=false,awake=false,sceneDef={revision:0,css:'',layers:[],nodes:[],features:{}},sceneRevision=-1;
let model={status:'cold',latency:'',reply:{text:'',done:true},draft:{text:''},voice:{active:false},bus:{event:''},seat:{},acoustic:{},activity:{serial:0,items:[],text:'',pc:{}},pc:{}};
let streamId=crypto.randomUUID(),revision=0,bootPromise=null,recovering=false,recoverBackoff=120,screenEpoch=0,replyEpoch=0,activityEpoch=0,composing=false,pendingText=null,textSending=false;
let micOn=false,micStream=null,audioCtx=null,processor=null,source=null,audioQueue=[],audioQueuedBytes=0,audioSending=false,voiceWanted=false,voiceEpoch=0,holdTimer=0,holdStarted=false,keyPointer=null;
const MAX_AUDIO_BYTES=192000,sleep=ms=>new Promise(r=>setTimeout(r,ms)),now=()=>performance.now();
const rand=n=>{const a=crypto.getRandomValues(new Uint8Array(n));let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
function path(o,p){let v=o;for(const k of String(p||'').split('.')){if(!k)continue;if(v==null)return '';v=v[k]}return v==null?'':v}
function fitViewport(){const v=visualViewport;if(!v){root.style.height='100%';root.style.top='0';return}root.style.height=Math.max(1,v.height)+'px';root.style.top=Math.max(0,v.offsetTop)+'px'}
fitViewport();visualViewport?.addEventListener('resize',fitViewport);visualViewport?.addEventListener('scroll',fitViewport);
function remember(){if(bridge&&token)localStorage.setItem('archie.phone.v7',JSON.stringify({bridge,token,at:Date.now()}))}
function recall(){try{const v=JSON.parse(localStorage.getItem('archie.phone.v7')||'{}');if(v.bridge&&v.token&&Date.now()-(v.at||0)<604800000){bridge=v.bridge;token=v.token;return true}}catch(_){}return false}
function forgetBridge(){bridge='';token='';session=false;replyEpoch++;activityEpoch++;screen.classList.remove('live');screen.removeAttribute('src')}
function timeoutFetch(url,opt={},ms=2200){const ac=new AbortController(),tm=setTimeout(()=>ac.abort(),ms);return fetch(url,{cache:'no-store',...opt,signal:ac.signal}).finally(()=>clearTimeout(tm))}
function localSelfTest(){const c={crypto:!!globalThis.crypto?.getRandomValues,fetch:typeof fetch==='function',stream:!!ReadableStream,canvas:!!ctx,storage:true,audio:!!navigator.mediaDevices?.getUserMedia,pointer:typeof PointerEvent!=='undefined',viewport:!!visualViewport};try{localStorage.setItem('archie.phone.probe','1');localStorage.removeItem('archie.phone.probe')}catch(_){c.storage=false}return{ok:Object.values(c).every(Boolean),checks:c}}
async function tailGet(p,ms=1600){const r=await timeoutFetch(TAIL+p,{},ms);if(!r.ok)throw Error('tail '+r.status);return r.json()}
async function tailPost(p,o,ms=3500){const r=await timeoutFetch(TAIL+p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(o)},ms);let v={};try{v=await r.json()}catch(_){}if(!r.ok)throw Error('tail '+r.status);return v}
async function action(o){o.agent=agent;return tailPost('/action',o,5000)}
async function api(p,opt={},ms=2200){if(!bridge||!token)throw Error('bridge absent');const t=now(),r=await timeoutFetch(bridge+p,{...opt,headers:{...(opt.headers||{}),'Authorization':'Bearer '+token}},ms);model.latency=Math.round(now()-t)+'ms';return r}
function ensureCanvas(){const dpr=Math.max(1,Math.min(3,devicePixelRatio||1)),w=root.clientWidth,h=root.clientHeight,nw=Math.round(w*dpr),nh=Math.round(h*dpr);if(canvas.width!==nw||canvas.height!==nh){canvas.width=nw;canvas.height=nh;canvas.style.width=w+'px';canvas.style.height=h+'px'}ctx.setTransform(dpr,0,0,dpr,0,0)}
function num(v,d=0){if(typeof v==='number')return v;if(typeof v==='string'){const n=Number(path(model,v));return Number.isFinite(n)?n:d}return d}
function draw(){ensureCanvas();const w=root.clientWidth,h=root.clientHeight;ctx.clearRect(0,0,w,h);for(const n of Array.isArray(sceneDef.nodes)?sceneDef.nodes:[]){if(!n||typeof n!=='object'||(n.when&&!path(model,n.when)))continue;ctx.globalAlpha=Math.max(0,Math.min(1,num(n.alpha,1)));ctx.fillStyle=String(n.fill||'rgba(255,255,255,.12)');ctx.strokeStyle=String(n.stroke||'rgba(255,255,255,.35)');ctx.lineWidth=Math.max(.25,num(n.line,1));const x=num(n.x,.5)*w,y=num(n.y,.5)*h,r=num(n.r,.02)*Math.min(w,h);if(n.kind==='disc'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}else if(n.kind==='ring'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke()}else if(n.kind==='grid'){const cols=Math.max(1,Math.floor(num(n.cols,3))),rows=Math.max(1,Math.floor(num(n.rows,3))),sx=num(n.sx,.02)*w,sy=num(n.sy,.02)*h;for(let iy=0;iy<rows;iy++)for(let ix=0;ix<cols;ix++){ctx.beginPath();ctx.arc(x+(ix-(cols-1)/2)*sx,y+(iy-(rows-1)/2)*sy,r,0,Math.PI*2);ctx.fill()}}}ctx.globalAlpha=1;requestAnimationFrame(draw)}
requestAnimationFrame(draw);
function buildLayers(){layers.replaceChildren();for(const d of Array.isArray(sceneDef.layers)?sceneDef.layers:[]){if(!d?.id)continue;const el=document.createElement('div');el.className='scene-layer '+String(d.class||'');el.dataset.sceneId=String(d.id);if(d.style&&typeof d.style==='object')Object.assign(el.style,d.style);layers.appendChild(el)}}
function render(){for(const d of Array.isArray(sceneDef.layers)?sceneDef.layers:[]){const el=layers.querySelector('[data-scene-id="'+CSS.escape(String(d.id))+'"]');if(!el)continue;let v=path(model,d.bind||'');if(d.map&&Object.prototype.hasOwnProperty.call(d.map,String(v)))v=d.map[String(v)];if(typeof d.prefix==='string'&&v!=='')v=d.prefix+v;if(typeof d.suffix==='string'&&v!=='')v=v+d.suffix;const text=String(v??'');el.textContent=text;el.hidden=!!d.hideEmpty&&!text}}
function applyScene(v){if(!v||typeof v!=='object')return;const sig=JSON.stringify(v);if(Number(v.revision||0)===sceneRevision&&sig===JSON.stringify(sceneDef))return;sceneDef=v;sceneRevision=Number(v.revision||0);sceneStyle.textContent=String(v.css||'').slice(0,100000);buildLayers();render()}
function activityText(v){const glyph={code:'λ',action:'↦',input:'←',output:'→',focus:'⌁',occupant:'○',bridge:'·',presence:'●'};return (Array.isArray(v?.items)?v.items:[]).slice(-7).map(x=>{let s=(glyph[x.kind]||'·')+' '+String(x.label||'');if(x.detail)s+='  '+String(x.detail);if(x.status&&x.status!=='stream')s+='  ['+String(x.status)+']';return s}).join('\n')}
function applyActivity(v){if(!v||typeof v!=='object')return;model.activity={...v,text:activityText(v)};model.pc=v.pc||{};render()}
async function loadStaticScene(){try{const u=new URL('phone_scene.json',location.href);u.searchParams.set('t',Date.now());const r=await timeoutFetch(u.href,{},1500);if(r.ok)applyScene(await r.json())}catch(_){}}
loadStaticScene();setInterval(()=>{if(!session)loadStaticScene()},1800);
async function remoteSelfTest(){const a=await api('/api/selftest',{},1500);if(!a.ok)throw Error('remote selftest');const s=await a.json();if(!s.ok)throw Error('remote selftest');const h=await api('/api/health',{},1500);if(!h.ok||(await h.json()).ok!==true)throw Error('remote health');model.selftest=s}
async function openSession(){await remoteSelfTest();const r=await api('/api/session',{method:'POST'},1800);if(!r.ok)throw Error('session');session=true;remember();recoverBackoff=120;model.status='live';startScreen();startReplyStream();startActivityStream();flushText();flushAudio();sendVoiceState(voiceWanted)}
function startScreen(){if(!bridge||!token)return;screenEpoch++;screen.src=bridge+'/api/screen.mjpg?t='+encodeURIComponent(token)+'&e='+screenEpoch;screen.classList.add('live')}
screen.onerror=()=>{screen.classList.remove('live');if(session)setTimeout(startScreen,140)};
async function startReplyStream(){const epoch=++replyEpoch;try{const r=await fetch(bridge+'/api/reply.ndjson',{cache:'no-store',headers:{'Authorization':'Bearer '+token,'Accept':'application/x-ndjson'}});if(!r.ok||!r.body)throw Error('reply stream');const reader=r.body.getReader(),dec=new TextDecoder();let buf='';while(session&&epoch===replyEpoch){const {value,done}=await reader.read();if(done)throw Error('reply eof');buf+=dec.decode(value,{stream:true});for(;;){const i=buf.indexOf('\n');if(i<0)break;const line=buf.slice(0,i);buf=buf.slice(i+1);if(!line)continue;let v;try{v=JSON.parse(line)}catch(_){continue}if(v.type==='reply'){model.reply=v.reply||{};model.seat=v.seat||{};model.acoustic=v.acoustic||{};model.status='live';render()}}}}catch(_){if(epoch===replyEpoch&&session){session=false;model.status='recovering';render()}}}
async function startActivityStream(){const epoch=++activityEpoch;try{const r=await fetch(bridge+'/api/activity.ndjson',{cache:'no-store',headers:{'Authorization':'Bearer '+token,'Accept':'application/x-ndjson'}});if(!r.ok||!r.body)throw Error('activity stream');const reader=r.body.getReader(),dec=new TextDecoder();let buf='';while(session&&epoch===activityEpoch){const {value,done}=await reader.read();if(done)throw Error('activity eof');buf+=dec.decode(value,{stream:true});for(;;){const i=buf.indexOf('\n');if(i<0)break;const line=buf.slice(0,i);buf=buf.slice(i+1);if(!line)continue;let v;try{v=JSON.parse(line)}catch(_){continue}if(v.type==='activity')applyActivity(v)}}}catch(_){if(epoch===activityEpoch&&session)setTimeout(()=>{if(session&&epoch===activityEpoch)startActivityStream()},180)}}
async function rendezvous(){for(let i=0;i<110;i++){try{const r=await timeoutFetch('https://ntfy.sh/'+encodeURIComponent(topic)+'/json?poll=1&since=all',{},1450);if(r.ok){const txt=await r.text();for(const line of txt.trim().split('\n').reverse()){try{const v=JSON.parse(line),m=JSON.parse(v.message||'{}');if(m.url&&m.token===token)return String(m.url).replace(/\/$/,'')}catch(_){}}}}catch(_){}try{const w=await tailGet('/windows',1100),m=JSON.stringify(w).match(/https:\/\/[a-z0-9-]+\.trycloudflare\.com/i);if(m)return m[0]}catch(_){}await sleep(220)}throw Error('rendezvous')}
async function bootstrap(){if(bootPromise)return bootPromise;bootPromise=(async()=>{const local=localSelfTest();if(!local.ok)throw Error('local selftest');const h=await tailGet('/seat/head',1500);if(!h||h.error||!h.active_occupant)throw Error('controller selftest');agent=h.active_occupant||agent;token=rand(32);topic='archie-'+rand(18).toLowerCase();
const base=RAW+'phone_bridge.py',fast=RAW+'phone_bridge_fast.py',acoustic=RAW+'acoustic_field.py',activity=RAW+'activity_field.py';
const cmd=`powershell -NoProfile -ExecutionPolicy Bypass -Command "$d=Join-Path $env:TEMP 'ArchiePhone';New-Item -ItemType Directory -Force $d|Out-Null;Get-CimInstance Win32_Process|? {$_.Name -match '^python' -and $_.CommandLine -like '*phone_bridge*.py*'}|% {Stop-Process -Id $_.ProcessId -Force};Invoke-WebRequest -UseBasicParsing '${base}' -OutFile (Join-Path $d 'phone_bridge.py');Invoke-WebRequest -UseBasicParsing '${fast}' -OutFile (Join-Path $d 'phone_bridge_fast.py');Invoke-WebRequest -UseBasicParsing '${acoustic}' -OutFile (Join-Path $d 'acoustic_field.py');Invoke-WebRequest -UseBasicParsing '${activity}' -OutFile (Join-Path $d 'activity_field.py');Set-Location $d;py -3.12 phone_bridge_fast.py --token '${token}' --topic '${topic}'"`;
await action({action:'clipboard_set',text:cmd,value:cmd,clipboard:cmd});await action({action:'hotkey',keys:['win','r']});await sleep(180);await action({action:'hotkey',keys:['ctrl','v']});await sleep(60);await action({action:'key',key:'enter'});bridge=await rendezvous();await openSession()})().finally(()=>bootPromise=null);return bootPromise}
async function recoverForever(){if(recovering)return;recovering=true;for(;;){if(session){await sleep(220);continue}model.status='recovering';render();try{if(bridge&&token){try{await openSession();continue}catch(_){forgetBridge()}}if(!bridge)recall();if(bridge&&token){try{await openSession();continue}catch(_){forgetBridge()}}if(awake&&navigator.onLine){await bootstrap();continue}}catch(_){}await sleep(recoverBackoff);recoverBackoff=Math.min(5000,Math.round(recoverBackoff*1.5))}}
recoverForever();
function kick(){awake=true;recoverBackoff=40;if(!session&&!bridge&&!bootPromise)bootstrap().catch(()=>{})}
async function stateLoop(){for(;;){if(!session){await sleep(100);continue}try{const r=await api('/api/state?x='+Date.now(),{},1450);if(!r.ok)throw Error('state');const s=await r.json();model.bus=s.bus||{};if(s.activity)applyActivity(s.activity);if(s.scene)applyScene(s.scene);render();await sleep(520)}catch(_){session=false;model.status='recovering';render();await sleep(60)}}}
stateLoop();
function queueText(final=false){const text=ink.value.replace(/\u00a0/g,' ');model.draft={text};render();revision++;pendingText={stream_id:streamId,revision,text,final};flushText();if(final){ink.value='';model.draft={text:''};streamId=crypto.randomUUID();revision=0;render()}}
async function flushText(){if(textSending||!session||!pendingText)return;textSending=true;try{while(session&&pendingText){const p=pendingText;pendingText=null;const r=await api('/api/text-stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)},1050);if(!r.ok)throw Error('text')}}catch(_){session=false}finally{textSending=false}}
ink.addEventListener('compositionstart',()=>composing=true);ink.addEventListener('compositionend',()=>{composing=false;queueText(false)});ink.addEventListener('input',()=>{kick();if(!composing)queueText(false)});ink.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();queueText(true)}});
function resample(input,from,to=16000){if(from===to)return input;const ratio=from/to,n=Math.max(1,Math.floor(input.length/ratio)),out=new Float32Array(n);for(let i=0;i<n;i++){const a=Math.floor(i*ratio),b=Math.min(input.length-1,Math.floor((i+1)*ratio));let sum=0,c=0;for(let j=a;j<=b;j++){sum+=input[j];c++}out[i]=c?sum/c:0}return out}
function pcm16(f){const a=new Int16Array(f.length);for(let i=0;i<f.length;i++){const x=Math.max(-1,Math.min(1,f[i]));a[i]=x<0?x*32768:x*32767}return a.buffer}
function queueAudio(b){audioQueue.push(b);audioQueuedBytes+=b.byteLength;while(audioQueuedBytes>MAX_AUDIO_BYTES&&audioQueue.length){const q=audioQueue.shift();audioQueuedBytes-=q.byteLength}flushAudio()}
async function flushAudio(){if(audioSending||!session||!audioQueue.length)return;audioSending=true;try{while(session&&audioQueue.length){const b=audioQueue[0],r=await api('/api/audio?rate=16000',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:b},1250);if(!r.ok)throw Error('audio');audioQueue.shift();audioQueuedBytes-=b.byteLength}}catch(_){session=false}finally{audioSending=false}}
function sendVoiceState(active){if(!session)return;api('/api/voice-state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:!!active})},700).catch(()=>{session=false})}
async function startMic(epoch){if(micOn||!voiceWanted||epoch!==voiceEpoch)return;let stream=null,ac=null,src=null,proc=null;try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(!voiceWanted||epoch!==voiceEpoch){stream.getTracks().forEach(t=>t.stop());return}ac=new(window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});if(ac.state==='suspended')await ac.resume();if(!voiceWanted||epoch!==voiceEpoch){stream.getTracks().forEach(t=>t.stop());await ac.close().catch(()=>{});return}src=ac.createMediaStreamSource(stream);proc=ac.createScriptProcessor(1024,1,1);proc.onaudioprocess=e=>{if(micOn&&voiceWanted&&epoch===voiceEpoch)queueAudio(pcm16(resample(e.inputBuffer.getChannelData(0),ac.sampleRate,16000)))};src.connect(proc);proc.connect(ac.destination);micStream=stream;audioCtx=ac;source=src;processor=proc;micOn=true;model.voice={active:true};key.classList.add('held');render()}catch(_){if(stream)stream.getTracks().forEach(t=>t.stop());if(ac)await ac.close().catch(()=>{});if(epoch===voiceEpoch){model.voice={active:false};key.classList.remove('held');render()}}}
function stopMic(){micOn=false;model.voice={active:false};key.classList.remove('held');render();if(processor)try{processor.disconnect()}catch(_){}if(source)try{source.disconnect()}catch(_){}if(micStream)micStream.getTracks().forEach(t=>t.stop());if(audioCtx)audioCtx.close().catch(()=>{});processor=source=micStream=audioCtx=null}
function beginHold(){holdStarted=true;voiceWanted=true;const epoch=++voiceEpoch;sendVoiceState(true);startMic(epoch)}
function endHold(){voiceWanted=false;++voiceEpoch;sendVoiceState(false);stopMic();holdStarted=false}
function keyDown(e){e.preventDefault();kick();keyPointer=e.pointerId;holdStarted=false;clearTimeout(holdTimer);holdTimer=setTimeout(beginHold,145);try{key.setPointerCapture(e.pointerId)}catch(_){}}
function keyUp(e){if(keyPointer!==null&&e.pointerId!==keyPointer)return;e.preventDefault();clearTimeout(holdTimer);keyPointer=null;if(holdStarted||voiceWanted||micOn){endHold();return}if(ink.value.trim())queueText(true);else{ink.focus({preventScroll:true});kick()}}
key.addEventListener('pointerdown',keyDown);key.addEventListener('pointerup',keyUp);key.addEventListener('pointercancel',e=>{e.preventDefault();clearTimeout(holdTimer);keyPointer=null;if(holdStarted||voiceWanted||micOn)endHold()});key.addEventListener('contextmenu',e=>e.preventDefault());
ink.addEventListener('focus',kick);window.addEventListener('online',()=>{session=false;replyEpoch++;activityEpoch++;recoverBackoff=60});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(voiceWanted||micOn)endHold()}else{session=false;replyEpoch++;activityEpoch++;recoverBackoff=60;loadStaticScene();fitViewport()}});
})();